# Generated by Django 4.2.3 on 2023-08-06 13:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Touchpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '触点',
                'verbose_name_plural': '触点',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片地址')),
                ('text', models.TextField(blank=True, null=True, verbose_name='展示文字')),
                ('jump_link', models.URLField(blank=True, null=True, verbose_name='跳转链接')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('available', models.BooleanField(db_index=True, default=False, verbose_name='启用')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('touchpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ad.touchpoint', verbose_name='触点')),
            ],
            options={
                'verbose_name': '推广内容',
                'verbose_name_plural': '推广内容',
            },
        ),
    ]
