# Generated by Django 4.2.3 on 2023-08-10 15:33

import ad.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=ad.storage.QiniuStorage(child_name='upload'), upload_to='', verbose_name='图片地址'),
        ),
    ]
