# Generated by Django 4.2.4 on 2023-08-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_alter_promotion_touchpoint_delete_touchpoint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.UniqueConstraint(condition=models.Q(('available', True)), fields=('touchpoint',), name='touchpoint_one_online'),
        ),
    ]
