# Generated by Django 4.2.4 on 2023-08-12 14:35

import ad.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_promotion_touchpoint_one_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='external_image',
            field=models.URLField(blank=True, null=True, verbose_name='外部图片地址'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=ad.storage.QiniuStorage(child_name='upload'), upload_to='', verbose_name='内部图片'),
        ),
    ]
