# Generated by Django 4.1 on 2022-08-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lowercase',
            field=models.BooleanField(default=False, verbose_name='转小写'),
        ),
    ]
