# Generated by Django 4.2.4 on 2023-09-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_userprofile_suspended_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='活跃时间'),
        ),
    ]
