# Generated by Django 3.2.3 on 2021-09-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcourse_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reply',
            field=models.TextField(blank=True, max_length=817, null=True, verbose_name='回复'),
        ),
    ]
