# Generated by Django 3.2.3 on 2021-09-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcourse_api', '0003_auto_20210913_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='abbr_pinyin',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='拼音缩写'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pinyin',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='拼音'),
        ),
    ]
