# Generated by Django 3.2.7 on 2021-09-17 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jcourse_api', '0004_auto_20210915_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': '评论点赞', 'verbose_name_plural': '评论点赞'},
        ),
    ]
