# Generated by Django 3.2.7 on 2021-09-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcourse_api', '0005_alter_action_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='职称'),
        ),
    ]
