# Generated by Django 3.2.7 on 2021-09-23 13:31

import django.core.validators
from django.db import migrations, models


def update_review_rating(apps, schema_editor):
    Review = apps.get_model('jcourse_api', 'Review')
    Review.objects.filter(rating=0).update(rating=1)


class Migration(migrations.Migration):
    dependencies = [
        ('jcourse_api', '0007_auto_20210922_2212'),
    ]

    operations = [
        migrations.RunPython(update_review_rating),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)],
                verbose_name='推荐指数'),
        ),
    ]
