# Generated by Django 3.2.9 on 2021-11-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcourse_api', '0009_alter_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='发布时间'),
        ),
    ]
