# Generated by Django 3.2.9 on 2021-12-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jcourse_api', '0009_alter_review_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
