# Generated by Django 3.2.10 on 2021-12-15 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('jcourse_api', '0010_auto_20211207_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.IntegerField(choices=[(1, '赞同'), (-1, '反对'), (0, '重置')], db_index=True, default=0,
                                      verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_count',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='点评数'),
        ),
        migrations.AlterField(
            model_name='formercode',
            name='new_code',
            field=models.CharField(db_index=True, max_length=32, verbose_name='新课号'),
        ),
        migrations.AlterField(
            model_name='formercode',
            name='old_code',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='旧课号'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='report',
            name='solved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否解决'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
    ]
