# Generated by Django 3.2.10 on 2021-12-16 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('jcourse_api', '0011_auto_20211215_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': '点评点赞', 'verbose_name_plural': '点评点赞'},
        ),
    ]
