# Generated by Django 3.2.10 on 2021-12-16 09:02

from django.db import migrations, models


def update_filter_count(apps, schema_editor):
    Course = apps.get_model('jcourse_api', 'Course')
    Category = apps.get_model('jcourse_api', 'Category')
    Department = apps.get_model('jcourse_api', 'Department')
    categories = Category.objects.all()
    departments = Department.objects.all()
    for category in categories:
        category.count = Course.objects.filter(category=category).count()
        category.save()
    for department in departments:
        department.count = Course.objects.filter(department=department).count()
        department.save()


class Migration(migrations.Migration):
    dependencies = [
        ('jcourse_api', '0012_alter_action_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.IntegerField(default=0, verbose_name='课程数量'),
        ),
        migrations.AddField(
            model_name='department',
            name='count',
            field=models.IntegerField(default=0, verbose_name='课程数量'),
        ),
        migrations.RunPython(update_filter_count),
    ]
