# Generated by Django 3.2.10 on 2021-12-22 14:10
from datetime import datetime, timezone

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.db.models import Sum


def make_up_old_point(apps, schema_editor):
    Review = apps.get_model('jcourse_api', 'Review')
    UserPoint = apps.get_model('jcourse_api', 'UserPoint')
    reviews = Review.objects.filter(created__lte=datetime(2021, 12, 12, tzinfo=timezone.utc))
    users = reviews.order_by('user').distinct('user').values_list('user', flat=True)
    for user in users:
        user_reviews = reviews.filter(user_id=user)
        courses = user_reviews.values_list('course', flat=True)
        approves_count = user_reviews.aggregate(count=Sum('approve_count'))['count']
        if approves_count is None:
            approves_count = 0
        first_reviews = reviews.filter(course__in=courses).order_by('course_id', 'created').distinct(
            'course_id').values_list('id', flat=True)
        first_reviews = first_reviews.intersection(user_reviews)
        first_reviews_approves_count = reviews.filter(pk__in=first_reviews).aggregate(count=Sum('approve_count'))[
            'count']
        if first_reviews_approves_count is None:
            first_reviews_approves_count = 0
        # print(user, approves_count, first_reviews_approves_count)
        value = approves_count + first_reviews_approves_count
        UserPoint.objects.create(user_id=user, value=value, description='升级补偿')


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jcourse_api', '0013_auto_20211216_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='数值')),
                ('description', models.CharField(max_length=255, verbose_name='原因')),
                ('time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '积分',
                'verbose_name_plural': '积分',
            },
        ),
        migrations.RunPython(make_up_old_point),
    ]
