# Generated by Django 4.0 on 2021-12-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jcourse_api', '0014_userpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoint',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='原因'),
        ),
    ]
