# Generated by Django 4.0 on 2022-01-05 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('jcourse_api', '0015_alter_userpoint_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollcourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userpoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='用户'),
        ),
    ]
