# Generated by Django 4.0.1 on 2022-01-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jcourse_api', '0016_alter_enrollcourse_user_alter_userpoint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='modified',
            field=models.DateTimeField(db_index=True, blank=True, null=True, verbose_name='修改时间'),
        ),
    ]
