# Generated by Django 4.0.1 on 2022-01-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jcourse_api', '0018_course_last_semester_teacher_last_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='review_avg',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True, verbose_name='平均评分'),
        ),
        migrations.AlterField(
            model_name='review',
            name='approve_count',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='获赞数'),
        ),
        migrations.AlterField(
            model_name='review',
            name='disapprove_count',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='获踩数'),
        ),
    ]
