# Generated by Django 4.0.1 on 2022-01-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jcourse_api', '0019_alter_course_review_avg_alter_review_approve_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=1926, verbose_name='详细点评'),
        ),
    ]
