# Generated by Django 4.0.1 on 2022-01-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jcourse_api', '0020_alter_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='available',
            field=models.BooleanField(default=True, verbose_name='用户可选'),
        ),
    ]
