# Generated by Django 4.0.5 on 2022-07-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jcourse_api', '0022_update_point_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='url',
            field=models.TextField(max_length=256, null=True, blank=True, verbose_name='链接'),
        ),
    ]
