# Generated by Django 4.0.6 on 2022-07-23 08:56

from django.db import migrations, models


def move_category_to_categories(apps, schema_editor):
    Course = apps.get_model('jcourse_api', 'Course')
    courses = Course.objects.all()
    for course in courses:
        category = course.category
        if category:
            course.categories.add(category)
            course.save()


class Migration(migrations.Migration):
    dependencies = [
        ('jcourse_api', '0024_alter_review_ordered_rule_'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(db_index=True, to='jcourse_api.category', verbose_name='类别'),
        ),
        migrations.RunPython(move_category_to_categories),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
    ]
