# Generated by Django 4.0.6 on 2022-07-24 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('jcourse_api', '0025_remove_course_category_course_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='count',
        ),
        migrations.RemoveField(
            model_name='department',
            name='count',
        ),
    ]
