# Generated by Django 4.1 on 2022-08-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jcourse_api', '0026_remove_category_count_remove_department_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, db_index=True, to='jcourse_api.category', verbose_name='类别'),
        ),
    ]
