# Generated by Django 4.1.1 on 2022-09-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcourse_api', '0027_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=9681, verbose_name='详细点评'),
        ),
    ]
