# Generated by Django 4.1.2 on 2022-10-24 05:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jcourse_api', '0028_alter_review_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='推荐指数')),
                ('comment', models.TextField(max_length=9681, verbose_name='详细点评')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='修订时间')),
                ('score', models.CharField(blank=True, max_length=10, null=True, verbose_name='成绩')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jcourse_api.course', verbose_name='课程')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jcourse_api.review', verbose_name='点评')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jcourse_api.semester', verbose_name='上课学期')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行用户')),
            ],
            options={
                'verbose_name': '点评修订记录',
                'verbose_name_plural': '点评修订记录',
            },
        ),
    ]
