# Generated by Django 4.1.2 on 2022-10-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcourse_api', '0029_reviewrevision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-modified'], 'verbose_name': '点评点赞', 'verbose_name_plural': '点评点赞'},
        ),
        migrations.AddField(
            model_name='action',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='修改时间'),
        ),
    ]
