# Generated by Django 4.1.2 on 2022-10-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jcourse_api', '0030_alter_action_options_action_modified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notice',
            new_name='Announcement',
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created'], 'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
    ]
