# Generated by Django 4.1.2 on 2022-11-01 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jcourse_api', '0031_rename_notice_announcement_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action',
            new_name='ReviewReaction',
        ),
        migrations.AlterModelOptions(
            name='reviewreaction',
            options={'ordering': ['-modified'], 'verbose_name': '点评回应', 'verbose_name_plural': '点评回应'},
        ),
        migrations.RenameField(
            model_name='reviewreaction',
            old_name='action',
            new_name='reaction',
        ),
        migrations.RemoveConstraint(
            model_name='reviewreaction',
            name='unique_action',
        ),
        migrations.AddConstraint(
            model_name='reviewreaction',
            constraint=models.UniqueConstraint(fields=('user', 'review'), name='unique_reaction'),
        ),
    ]
