# Generated by Django 4.1.2 on 2022-11-02 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jcourse_api', '0032_rename_action_reviewreaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, choices=[(0, '管理员回复'), (1, '获得点赞'), (2, '积分失效'), (3, '积分补偿'), (4, '点评被回复'), (5, '点评被引用'), (6, '点评被删除'), (7, '反馈被回复'), (8, '关注的课程有新点评')], db_index=True, null=True, verbose_name='类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('object_id', models.PositiveIntegerField(null=True, verbose_name='内容ID')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='阅读时间')),
                ('public', models.BooleanField(db_index=True, default=True, verbose_name='已发布')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='内容类型')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ('-created',),
            },
        ),
    ]
