# Generated by Django 4.1.2 on 2022-11-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcourse_api', '0033_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewreaction',
            name='reaction',
            field=models.IntegerField(choices=[(0, '重置'), (1, '赞同'), (-1, '反对')], db_index=True, default=0, verbose_name='操作'),
        ),
    ]
