# Generated by Django 4.1.2 on 2022-11-03 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jcourse_api', '0034_alter_reviewreaction_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollcourse',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
