# Generated by Django 4.1.2 on 2022-11-04 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jcourse_api", "0035_enrollcourse_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseNotificationLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_level",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "正常"), (1, "关注"), (2, "忽略")],
                        default=0,
                        verbose_name="通知等级",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="改动时间"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jcourse_api.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={"verbose_name": "课程通知等级", "verbose_name_plural": "课程通知等级",},
        ),
    ]
