# Generated by Django 4.1.5 on 2023-01-31 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jcourse_api', '0036_coursenotificationlevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',), 'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': '反馈', 'verbose_name_plural': '反馈'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-modified_at'], 'verbose_name': '点评', 'verbose_name_plural': '点评'},
        ),
        migrations.AlterModelOptions(
            name='reviewreaction',
            options={'ordering': ['-modified_at'], 'verbose_name': '点评回应', 'verbose_name_plural': '点评回应'},
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='apikey',
            old_name='last_modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='coursenotificationlevel',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='enrollcourse',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='reviewreaction',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='reviewrevision',
            old_name='created',
            new_name='created_at',
        ),
    ]
