# Generated by Django 4.1.7 on 2023-03-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcourse_api', '0037_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='formercode',
            constraint=models.UniqueConstraint(fields=('old_code', 'new_code'), name='unique_record'),
        ),
    ]
