# Generated by Django 4.1.6 on 2023-02-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcourse_api', '0037_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='锁定'),
        ),
    ]
