# Generated by Django 4.2.4 on 2023-08-12 12:59
import django
from django.contrib.postgres.search import SearchVector
from django.db import migrations

from utils.cut_word import get_cut_word_search_vector


def cut_for_exist_reviews(apps, schema_editor):
    Review = apps.get_model("jcourse_api", "Review")
    reviews = Review.objects.all()
    for review in reviews:
        review.search_vector = get_cut_word_search_vector(review.comment)
        review.save(update_fields=["search_vector"])
        print(review.id)


class Migration(migrations.Migration):
    dependencies = [
        ('jcourse_api', '0038_formercode_unique_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.RunPython(cut_for_exist_reviews, reverse_code=migrations.RunPython.noop)
    ]
