# Generated by Django 4.2.4 on 2023-08-25 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jcourse_api', '0040_review_jcourse_api_search__43d524_gin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrevision',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jcourse_api.review', verbose_name='点评'),
        ),
    ]
