# Generated by Django 4.2.7 on 2023-12-01 14:54
from django.contrib.auth.models import User
from django.db import migrations
from django.db.models import F

from jcourse_api.models import Review
from jcourse_api.utils.point import get_user_point_with_reviews


def get_user_point(user: User):
    reviews = Review.objects.filter(user=user).exclude(disapprove_count__gt=F('approve_count') * 2)
    return get_user_point_with_reviews(user, reviews)


def get_all_users_point(apps, schema_editor):
    UserPoint = apps.get_model('jcourse_api', 'UserPoint')
    users = User.objects.all()
    for user in users:
        old_point, new_point = get_user_point(user)
        diff = old_point - new_point
        if diff > 0:
            UserPoint.objects.create(user_id=user.id, value=diff, description='历史积分补偿')


class Migration(migrations.Migration):
    dependencies = [
        ('jcourse_api', '0041_alter_reviewrevision_review'),
    ]

    operations = [
        migrations.RunPython(get_all_users_point, reverse_code=migrations.RunPython.noop)
    ]
